version: ~> 1.0

language: python

env:
  global:
    - PYTHONIOENCODING: utf8

python:
  - '3.8'

before_install:
  - pip install -U requests

install:
  - mkdir -p /tmp/cvssdata

script: python run.py

cache:
  directories:
    - /tmp/cvssdata