version: ~> 1.0

language: python

env:
  global:
    - PYTHONIOENCODING: utf8

python:
  - '3.8'

before_install:
  - pip install -U requests

install:
  - mkdir -p /tmp/cvssdata

script: 
  - python run.py
  - zip -j /tmp/cvss.csv.zip /tmp/cvssdata/data.csv
  - curl https://v0.api.upyun.com/py3iodownload -F file=@/tmp/cvss.csv.zip -F policy=$UPYUN_POLICY -F signature=$UPYUN_SIGN

cache:
  directories:
    - /tmp/cvssdata